sonar.projectKey=DimonBel_Document-editor
sonar.projectName=Document Editor
sonar.projectVersion=0.1.0

sonar.sources=backend/src,frontend/src
sonar.tests=backend/src,frontend/src

sonar.sourceEncoding=UTF-8

sonar.rust.file.suffixes=.rs
sonar.javascript.file.suffixes=.js,.jsx,.ts,.tsx

sonar.exclusions=\
  backend/target/**,\
  frontend/node_modules/**,\
  frontend/dist/**,\
  **/*.min.js,\
  **/Cargo.lock

sonar.coverage.exclusions=\
  backend/src/main.rs,\
  frontend/src/main.tsx